const multipleCorrectQuestions = [
    {
      type: 'multiple',
      question: 'Which of the following are prime numbers?',
      options: ['4', '7', '12', '23'],
      correctAnswer: ['7', '23'],
      difficulty: 'easy',
      timeLimit: 30,
    },
    {
      type: 'multiple',
      question: 'Select the even numbers from the list.',
      options: ['3', '6', '9', '12'],
      correctAnswer: ['6', '12'],
      difficulty: 'medium',
      timeLimit: 40,
    },
    {
      type: 'multiple',
      question: 'Identify the prime numbers.',
      options: ['18', '29', '14', '5'],
      correctAnswer: ['29', '5'],
      difficulty: 'easy',
      timeLimit: 30,
    },
    {
      type: 'multiple',
      question: 'Choose the odd numbers.',
      options: ['20', '37', '16', '42'],
      correctAnswer: ['37'],
      difficulty: 'medium',
      timeLimit: 40,
    },
    {
      type: 'multiple',
      question: 'Pick the multiples of 5.',
      options: ['25', '14', '6', '35'],
      correctAnswer: ['25', '35'],
      difficulty: 'easy',
      timeLimit: 30,
    },
    {
      type: 'multiple',
      question: 'Which numbers are divisible by 3?',
      options: ['27', '18', '14', '22'],
      correctAnswer: ['27', '18'],
      difficulty: 'medium',
      timeLimit: 40,
    },
    {
      type: 'multiple',
      question: 'Select the prime numbers.',
      options: ['10', '19', '8', '31'],
      correctAnswer: ['19', '31'],
      difficulty: 'easy',
      timeLimit: 30,
    },
    {
      type: 'multiple',
      question: 'Identify the even numbers.',
      options: ['7', '14', '23', '30'],
      correctAnswer: ['14', '30'],
      difficulty: 'medium',
      timeLimit: 40,
    },
    {
      type: 'multiple',
      question: 'Choose the prime numbers.',
      options: ['12', '17', '21', '28'],
      correctAnswer: ['17'],
      difficulty: 'easy',
      timeLimit: 30,
    },
    {
      type: 'multiple',
      question: 'Pick the multiples of 4.',
      options: ['18', '27', '16', '20'],
      correctAnswer: ['16', '20'],
      difficulty: 'medium',
      timeLimit: 40,
    },
    {
      type: 'multiple',
      question: 'Which numbers are divisible by 2?',
      options: ['13', '8', '21', '16'],
      correctAnswer: ['8', '16'],
      difficulty: 'easy',
      timeLimit: 30,
    },
    {
      type: 'multiple',
      question: 'Select the odd numbers.',
      options: ['10', '19', '14', '22'],
      correctAnswer: ['19'],
      difficulty: 'medium',
      timeLimit: 40,
    },
    {
      type: 'multiple',
      question: 'Identify the multiples of 3.',
      options: ['18', '25', '14', '21'],
      correctAnswer: ['18', '21'],
      difficulty: 'easy',
      timeLimit: 30,
    },
    {
      type: 'multiple',
      question: 'Choose the prime numbers.',
      options: ['10', '23', '14', '31'],
      correctAnswer: ['23', '31'],
      difficulty: 'medium',
      timeLimit: 40,
    },
    {
      type: 'multiple',
      question: 'Pick the even numbers.',
      options: ['7', '14', '23', '30'],
      correctAnswer: ['14', '30'],
      difficulty: 'easy',
      timeLimit: 30,
    },
    {
      type: 'multiple',
      question: 'Select the odd numbers.',
      options: ['10', '19', '14', '22'],
      correctAnswer: ['19'],
      difficulty: 'medium',
      timeLimit: 40,
    },
    {
      type: 'multiple',
      question: 'Identify the multiples of 4.',
      options: ['18', '27', '16', '20'],
      correctAnswer: ['16', '20'],
      difficulty: 'easy',
      timeLimit: 30,
    },
    {
      type: 'multiple',
      question: 'Choose the prime numbers.',
      options: ['12', '17', '21', '28'],
      correctAnswer: ['17'],
      difficulty: 'medium',
      timeLimit: 40,
    },
    {
      type: 'multiple',
      question: 'Pick the even numbers.',
      options: ['7', '14', '23', '30'],
      correctAnswer: ['14', '30'],
      difficulty: 'easy',
    },
]
  

const trueFalseQuestions = [
    {
        type: 'truefalse',
        question: 'The sun rises in the west.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'Cats can fly.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'Water boils at 50 degrees Celsius.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'Mount Everest is the tallest mountain on Earth.',
        correctAnswer: 'true',
    },
    {
        type: 'truefalse',
        question: 'The Great Wall of China is visible from space.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'Bananas are berries.',
        correctAnswer: 'true',
    },
    {
        type: 'truefalse',
        question: 'The Earth is flat.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'Elephants can fly.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'The Eiffel Tower is in London.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'The Pacific Ocean is the largest ocean on Earth.',
        correctAnswer: 'true',
    },
    {
        type: 'truefalse',
        question: 'Venus is the closest planet to the Sun.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'Honey never spoils.',
        correctAnswer: 'true',
    },
    {
        type: 'truefalse',
        question: 'A group of crows is called a murder.',
        correctAnswer: 'true',
    },
    {
        type: 'truefalse',
        question: 'The moon is made of green cheese.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'The Great Barrier Reef is the largest coral reef in the world.',
        correctAnswer: 'true',
    },
    {
        type: 'truefalse',
        question: 'Spiders are insects.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'The Sahara Desert is the largest desert in the world.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'Penguins can fly.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'The Statue of Liberty is in Paris.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        question: 'Diamonds are made of compressed coal.',
        correctAnswer: 'false',
    },
];

module.exports = multipleCorrectQuestions;

  