const shortAnswerQuestions = [
    {
        type: 'shortanswer',
        question: 'What is the capital of France?',
        correctAnswer: 'Paris',
        difficulty: 'easy',
        timeLimit: 30, // in seconds
    },
    {
        type: 'shortanswer',
        question: 'What is the largest river in the world?',
        correctAnswer: 'Amazon',
        difficulty: 'easy',
        timeLimit: 30,
    },
    {
        type: 'shortanswer',
        question: 'Who wrote "Romeo and Juliet"?',
        correctAnswer: 'William Shakespeare',
        difficulty: 'easy',
        timeLimit: 30,
    },
    {
        type: 'shortanswer',
        question: 'What is the capital of Japan?',
        correctAnswer: 'Tokyo',
        difficulty: 'easy',
        timeLimit: 30,
    },
    {
        type: 'shortanswer',
        question: 'Name the largest ocean on Earth.',
        correctAnswer: 'Pacific',
        difficulty: 'easy',
        timeLimit: 30,
    },
    {
        type: 'shortanswer',
        question: 'What is the square root of 144?',
        correctAnswer: '12',
        difficulty: 'easy',
        timeLimit: 30,
    },
    {
        type: 'shortanswer',
        question: 'Who painted the Mona Lisa?',
        correctAnswer: 'Leonardo da Vinci',
        difficulty: 'medium',
        timeLimit: 45,
    },
    {
        type: 'shortanswer',
        question: 'In which year did World War II end?',
        correctAnswer: '1945',
        difficulty: 'medium',
        timeLimit: 45,
    },
    {
        type: 'shortanswer',
        question: 'What is the currency of Brazil?',
        correctAnswer: 'Brazilian Real',
        difficulty: 'medium',
        timeLimit: 45,
    },
    {
        type: 'shortanswer',
        question: 'Who discovered penicillin?',
        correctAnswer: 'Alexander Fleming',
        difficulty: 'medium',
        timeLimit: 45,
    },
    {
        type: 'shortanswer',
        question: 'What is the largest mammal on Earth?',
        correctAnswer: 'Blue Whale',
        difficulty: 'medium',
        timeLimit: 45,
    },
    {
        type: 'shortanswer',
        question: 'What is the capital of Australia?',
        correctAnswer: 'Canberra',
        difficulty: 'medium',
        timeLimit: 45,
    },
    {
        type: 'shortanswer',
        question: 'Who wrote "To Kill a Mockingbird"?',
        correctAnswer: 'Harper Lee',
        difficulty: 'hard',
        timeLimit: 60,
    },
    {
        type: 'shortanswer',
        question: 'What is the largest desert on Earth?',
        correctAnswer: 'Antarctica',
        difficulty: 'hard',
        timeLimit: 60,
    },
    {
        type: 'shortanswer',
        question: 'Who was the first woman to win a Nobel Prize?',
        correctAnswer: 'Marie Curie',
        difficulty: 'hard',
        timeLimit: 60,
    },
    {
        type: 'shortanswer',
        question: 'Which planet is known as the Red Planet?',
        correctAnswer: 'Mars',
        difficulty: 'hard',
        timeLimit: 60,
    },
    {
        type: 'shortanswer',
        question: 'Who was the first President of the United States?',
        correctAnswer: 'George Washington',
        difficulty: 'hard',
        timeLimit: 60,
    },
    {
        type: 'shortanswer',
        question: 'In which year did the Titanic sink?',
        correctAnswer: '1912',
        difficulty: 'hard',
        timeLimit: 60,
    },
    {
        type: 'shortanswer',
        question: 'Name the smallest prime number.',
        correctAnswer: '2',
        difficulty: 'hard',
        timeLimit: 60,
    },
];

module.exports = shortAnswerQuestions;