const trueFalseQuestions = [
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'The sun rises in the west.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'Cats can fly.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'Water boils at 50 degrees Celsius.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'Mount Everest is the tallest mountain on Earth.',
        correctAnswer: 'true',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'The Great Wall of China is visible from space.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'Bananas are berries.',
        correctAnswer: 'true',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'The Earth is flat.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'Elephants can fly.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'The Eiffel Tower is in London.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'The Pacific Ocean is the largest ocean on Earth.',
        correctAnswer: 'true',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'Venus is the closest planet to the Sun.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'Honey never spoils.',
        correctAnswer: 'true',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'A group of crows is called a murder.',
        correctAnswer: 'true',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'The moon is made of green cheese.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'The Great Barrier Reef is the largest coral reef in the world.',
        correctAnswer: 'true',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'Spiders are insects.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'The Sahara Desert is the largest desert in the world.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'Penguins can fly.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'The Statue of Liberty is in Paris.',
        correctAnswer: 'false',
    },
    {
        type: 'truefalse',
        difficulty: 'hard',
        timeLimit: 60,
        question: 'Diamonds are made of compressed coal.',
        correctAnswer: 'false',
    },
];

module.exports = trueFalseQuestions;